name: Linting

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
      - '.github/workflows/linting.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'
      - '.github/workflows/linting.yml'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Linting Tools
        run: pip install ruff mypy types-tqdm pydantic hatchling

      - name: Install package
        run: pip install -e .

      - name: Run Ruff
        run: |
          ruff check .
          ruff check --select D --config 'lint.pydocstyle.convention="google"' src/

      - name: Run Mypy
        run: mypy src/shorts_maker
